# redirecting the homepage
index:
    path: /
    controller: App\Controller\DashboardController::index

_demo:
    resource: "@SaadTaziGChartBundle/Resources/config/routing.yml"
    type:     yaml
    prefix:   /gchart